info:
  name: Get Settings
  type: http
  seq: 1

http:
  method: get
  url: "{{BaseURL}}/settings/"
  headers:
    - name: Accept
      value: application/json
  auth: inherit

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
